n1 = int(input("Enter a number: "))
n2 = int(input("Enter other number: "))

sum = (n1 + n2)
subtraction = (n1 - n2)
multiplication = (n1 * n2)
division = (n1 / n2)
exponentiation = (n1 ** n2)
intdivision = (n1 // n2)
modulus = (n1 % n2)

print("Results:")
print("sum: ",sum)
print("sub: ", subtraction)
print("multi: ",multiplication)
print("division: ",division)
print("expo: ",exponentiation)
print("intdivision: ",intdivision)
print("modulus: ",modulus)