some = input('Type something here: ')
print(type(some))
print("is numeric? ", some.isnumeric())
print("is alpha? ", some.isalpha())
print("is alnum? ", some.isalnum())
print("is upper? ", some.isupper())
print("is lower? ", some.islower())